package com.vci.vectorcamapp.imaging.domain.util

import com.vci.vectorcamapp.core.domain.util.Error

enum class ImagingError : Error {
    CAPTURE_ERROR,
    SAVE_ERROR,
    INVALID_SPECIMEN_ID,
    PROCESSING_ERROR,
    NO_SPECIMEN_FOUND,
    MULTIPLE_SPECIMENS_FOUND,
    NO_ACTIVE_SESSION,
    MODEL_INITIALIZATION_FAILED,
    GPU_DELEGATE_INITIALIZATION_FAILED,
    UNKNOWN_INITIALIZATION_ERROR,
    INVALID_INPUT_SHAPE,
    SPECIMEN_ID_RECOGNITION_FAILED,
    SPECIMEN_DETECTION_FAILED,
    UNKNOWN_INFERENCE_ERROR,
    UNKNOWN_ERROR;
}
