package com.vci.vectorcamapp.ui.theme

import androidx.compose.ui.graphics.Color

val primary = Color(0xFF6DCB81)
val onPrimary = Color(0xFFFFFFFF)
val secondary = Color(0xFF4DBD8C)
val onSecondary = Color(0xFFFFFFFF)
val accent = Color(0xFFE9F9F1)
val onAccent = Color(0xFF1A1A1A)
val surfaceContainer = Color(0xFFFFFFFF)
val background = Color(0xFFF6F6F6)
val onBackground = Color(0xFF1A1A1A)
val headerGradientTopLeft = Color(0xFFB6EAD8)
val headerGradientBottomRight = Color(0xFFD3F5DF)
val onHeader = Color(0xFF1A1A1A)
val onHeaderVariant = Color(0xFF5F6B6F)
val buttonGradientLeft = Color(0xFF57C88B)
val buttonGradientRight = Color(0xFF6EDB81)
val onButton = Color(0xFFFFFFFF)
val successConfirm = Color(0xFF6DCB81)
val onSuccessConfirm = Color(0xFFFFFFFF)
val error = Color(0xFFE54848)
val onError = Color(0xFFFFFFFF)
val fieldBorder = Color(0xFF48B746)
val divider = Color(0xFFD8EAD9)
